apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: movie-app
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: root
  SPRING_DATASOURCE_PASSWORD: rootpass
  JWT_SECRET: hQ3K6mFkR+ZnBkxkzOT/F9mAnfpRW5AfYlPj3APlSS8=
