apiVersion: apps/v1
kind: Deployment
metadata:
  name: showtime-service
  namespace: movie-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: showtime-service
  template:
    metadata:
      labels:
        app: showtime-service
    spec:
      containers:
        - name: showtime-service
          image: aakashpatel22/showtime-service:latest
          ports:
            - containerPort: 3004
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/movie_ticketing?createDatabaseIfNotExist=true
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: SPRING_DATASOURCE_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: JWT_SECRET
