apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: movie-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: aakashpatel22/user-service:latest
          ports:
            - containerPort: 3001
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "500m"
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/movie_ticketing?createDatabaseIfNotExist=true
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: SPRING_DATASOURCE_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: JWT_SECRET

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: user-service
#   namespace: movie-app
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: user-service
#   template:
#     metadata:
#       labels:
#         app: user-service
#     spec:
#       containers:
#         - name: user-service
#           image: aakashpatel22/user-service:latest
#           ports:
#             - containerPort: 3001
#           env:
#             - name: SPRING_DATASOURCE_URL
#               value: jdbc:mysql://mysql:3306/movie_ticketing?createDatabaseIfNotExist=true
#             - name: SPRING_DATASOURCE_USERNAME
#               valueFrom:
#                 secretKeyRef:
#                   name: app-secrets
#                   key: SPRING_DATASOURCE_USERNAME
#             - name: SPRING_DATASOURCE_PASSWORD
#               valueFrom:
#                 secretKeyRef:
#                   name: app-secrets
#                   key: SPRING_DATASOURCE_PASSWORD
#             - name: JWT_SECRET
#               valueFrom:
#                 secretKeyRef:
#                   name: app-secrets
#                   key: JWT_SECRET
